import streamlit as st
import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold

# --- 1. CONFIGURAZIONE PAGINA (PRIMA RIGA!) ---
st.set_page_config(page_title="Preventivatore TeamBuilding", page_icon="🦁", layout="centered")

# --- 2. CONFIGURAZIONE API ---
# La chiave viene letta dai "Secrets" di Streamlit
if "GOOGLE_API_KEY" in st.secrets:
    api_key = st.secrets["GOOGLE_API_KEY"]
else:
    st.error("Manca la API Key nei Secrets!")
    st.stop()

# --- 3. DEFINIZIONE PROMPT E DATABASE ---

system_instruction = """
### SEI L'ASSISTENTE VIRTUALE UFFICIALE DI TEAMBUILDING.IT.
Il tuo obiettivo è aiutare i visitatori a trovare l'attività perfetta e invogliarli a chiedere un preventivo al nostro staff umano.

### REGOLE DI SICUREZZA (TASSATIVE)
1. **NON PARLARE MAI DI PREZZI:** Tu non conosci i prezzi. Se ti chiedono "Quanto costa?", rispondi: "I costi dipendono da molti fattori (numero persone, data, location). Posso metterti in contatto con un nostro event manager per un preventivo su misura!".
2. **NON INVENTARE:** Usa SOLO i format elencati nel [DATABASE FORMAT] qui sotto. Se un format non c'è, di' che non è disponibile.
3. **LINK:** Su richiesta fornisci il link al sito web 

### FLUSSO DI CONVERSAZIONE
1. **ACCOGLIENZA:** Sii breve, empatico e professionale. Chiedi come puoi aiutare, che tipo di evento stanno organizzando, se hanno già delle idee in mente. In seconda battuta chiedi numero persone, obiettivo, periodo.
2. **CONSULENZA:** In base alle risposte, suggerisci **4 FORMAT** che siano perfetti per loro:
    * 1 Best Seller
    * 1 Novità
    * 1 Vibe (Mood adatto)
    * 1 Social
3. **PRESENTAZIONE FORMAT:**
    Usa questo schema per ogni suggerimento:
    > **[Nome Format]**
    > [Breve descrizione accattivante basata sulla colonna Descrizione]
    > *Perché ve lo consiglio:* [Tua motivazione legata alla loro richiesta]

4. **CHIUSURA (Call to Action):**
    Concludi sempre invitando a contattarci: *"Volete approfondire uno di questi o preferite altre idee?"*

### [DATABASE FORMAT - NO PREZZI]
"""

database_attivita = """
[
    {
        "nome": "5ensi",
        "format": "Sensoriale / Cena",
        "logistica": "Durante i pasti",
        "target": "Gruppi Internazionali, Cene Relax",
        "vibe": "Relax, Sensoriale, Scoperta",
        "hook": "Un viaggio sensoriale dove le parole non servono: contano solo le percezioni.",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 2.0,
        "durata_ideale": 1.5,
        "descrizione": "Sfida a squadre basata sull'uso dei 5 sensi per riconoscere oggetti e sapori.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/5ensi/"
    },
    {
        "nome": "Actors Studio",
        "format": "Teatrale / Creativo",
        "logistica": "Indoor",
        "target": "Team Commerciali, Estroversi",
        "vibe": "Creatività, Risate, Espressione",
        "hook": "Luci, camera, azione! Mettete in scena il talento nascosto del vostro team.",
        "social_activity": True,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 3.0,
        "durata_max": 6.0,
        "durata_ideale": 4.0,
        "descrizione": "I partecipanti scrivono, costumano e recitano brevi scene teatrali o spot.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/actors-studio/"
    },
    {
        "nome": "Affresco",
        "format": "Creativo / Artistico",
        "logistica": "Indoor / Outdoor",
        "target": "Team Creativi, Grandi Gruppi",
        "vibe": "Creatività, Collaborazione Pura, Relax",
        "hook": "Ogni pennellata è unica, ma è l'insieme che crea il capolavoro aziendale.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 3.0,
        "durata_ideale": 2.0,
        "descrizione": "Creazione di un grande dipinto collettivo su pannelli che formano un'unica opera.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/affresco/"
    },
    {
        "nome": "Agility Dog",
        "format": "Sociale / Costruzione",
        "logistica": "Outdoor",
        "target": "Amanti animali, Team Empatici",
        "vibe": "Cuore, Natura, Empatia",
        "hook": "Costruire per i nostri amici a 4 zampe: un team building che fa scodinzolare il cuore.",
        "social_activity": False,
        "novita": True,
        "ranking": 2,
        "max_pax": 50,
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione di un percorso a ostacoli per cani e dimostrazione finale con addestratori.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/agility-dog/"
    },
    {
        "nome": "AI TeamBuilders",
        "format": "Tech / AI",
        "logistica": "Indoor",
        "target": "Marketing, IT, Gen-Z, Innovatori",
        "vibe": "Innovazione, Futuro, Visionario",
        "hook": "Il futuro è adesso: collaborate con l'Intelligenza Artificiale per creare l'impossibile.",
        "social_activity": False,
        "novita": True,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Utilizzo dell'intelligenza artificiale per ideare e creare nuovi format o prodotti.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/ai-team-builders/"
    },
    {
        "nome": "Aliante",
        "format": "Esperienziale / Volo",
        "logistica": "Outdoor",
        "target": "Board Direzionale, Top Management",
        "vibe": "Adrenalina, Esclusività, Libertà",
        "hook": "Cambiate prospettiva e puntate in alto: un'esperienza di volo esclusiva e indimenticabile.",
        "social_activity": False,
        "novita": False,
        "ranking": 1,
        "max_pax": 50,
        "durata_min": 4.0,
        "durata_max": 8.0,
        "durata_ideale": 6.0,
        "descrizione": "Giornata in aeroclub con montaggio aliante, simulatore e prova di volo reale.",
        "formazione_level": "High",
        "note": "Si svolge solo a Bergamo in giornate prive di vento. Format complesso da organizzare.",
        "url": "https://www.teambuilding.it/project/aliante/"
    },
    {
        "nome": "Animal House",
        "format": "Sociale / Costruzione",
        "logistica": "Indoor / Outdoor",
        "target": "Team Empatici, CSR",
        "vibe": "Cuore, Manualità, Utilità",
        "hook": "Date una casa a chi non ce l'ha: manualità e cuore al servizio degli animali.",
        "social_activity": True,
        "novita": True,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 3.0,
        "durata_ideale": 2.0,
        "descrizione": "Costruzione e decorazione di cucce e casette per animali da donare a canili/gattili.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/animal-house/"
    },
    {
        "nome": "AperiBuilding",
        "format": "Culinario / Aperitivo",
        "logistica": "Indoor / Outdoor",
        "target": "Gruppi misti, Ice-breaking",
        "vibe": "Convivialità, Gusto, Relax",
        "hook": "Non il solito aperitivo, ma quello creato dalle vostre mani: shake your team!",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 2.5,
        "durata_ideale": 1.5,
        "descrizione": "Sfida culinaria per la creazione del miglior finger food e cocktail abbinato.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/aperibuilding/"
    },
    {
        "nome": "Auto Smash",
        "format": "Antistress",
        "logistica": "Outdoor",
        "target": "Team sotto pressione, Sales",
        "vibe": "Adrenalina, Sfogo, Potenza",
        "hook": "Avete avuto un anno stressante? E' il momento di distruggere tutto (letteralmente).",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": 50,
        "durata_min": 0.5,
        "durata_max": 1.5,
        "durata_ideale": 1.0,
        "descrizione": "Demolizione controllata di un'auto vera con mazze e martelli in totale sicurezza.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/auto-smash/"
    },
    {
        "nome": "Ballando",
        "format": "Danza / Show",
        "logistica": "Indoor",
        "target": "Estroversi, Party Aziendali",
        "vibe": "Energia, Risate, Movimento",
        "hook": "Il ritmo che unisce: scendete in pista e coordinatevi a tempo di musica.",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 3.0,
        "durata_ideale": 2.0,
        "descrizione": "Preparazione di una coreografia di ballo di gruppo con esibizione finale.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/ballando/"
    },
    {
        "nome": "Beach Club",
        "format": "Sportivo / Giochi",
        "logistica": "Outdoor",
        "target": "Giovani, Sportivi, Summer Party",
        "vibe": "Sole, Competizione, Divertimento",
        "hook": "Sole, mare e sana competizione: le olimpiadi da spiaggia per ricaricare le batterie.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Torneo di giochi da spiaggia (volley, bocce, castelli di sabbia, ecc.) in riva al mare.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/beach-club/"
    },
    {
        "nome": "Bike Building",
        "format": "Sociale / Costruzione",
        "logistica": "Indoor",
        "target": "Tutti i reparti, CSR",
        "vibe": "Cuore, Meccanica, Sorpresa",
        "hook": "Avvitare un bullone non è mai stato così emozionante: costruite un sorriso per un bambino.",
        "social_activity": True,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 2.0,
        "durata_ideale": 1.5,
        "descrizione": "Montaggio di biciclette da zero che verranno donate in beneficenza a fine evento.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/bike-building/"
    },
    {
        "nome": "Bootcamp",
        "format": "Avventura / Sport",
        "logistica": "Outdoor",
        "target": "Sportivi, Team 'aggressivi'",
        "vibe": "Adrenalina, Fatica, Superamento Limiti",
        "hook": "Oltre ogni limite: addestramento militare per forgiare un carattere di ferro.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 3.0,
        "durata_max": 6.0,
        "durata_ideale": 4.0,
        "descrizione": "Percorso di sopravvivenza e prove fisiche/logiche ispirate all'addestramento militare.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/bootcamp/"
    },
    {
        "nome": "Caccia all'uomo",
        "format": "Urban Game / Avventura",
        "logistica": "Outdoor",
        "target": "Sportivi, team agguerriti",
        "vibe": "Sport, velocità, rapidità, competizione",
        "hook": "Caccia all’uomo è il team building che trasforma la città in un set da thriller.",
        "social_activity": False,
        "novita": True,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 4.0,
        "durata_ideale": 2.5,
        "descrizione": "Inseguite e catturate un personaggio misterioso in città.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/caccia-alluomo/"
    },
    {
        "nome": "Candid Camera",
        "format": "Creativo / Urban",
        "logistica": "Outdoor",
        "target": "Team Commerciali, Estroversi",
        "vibe": "Risate, Faccia tosta, Creatività",
        "hook": "Siete pronti a metterci la faccia? Il team building più irriverente di sempre.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": 150,
        "durata_min": 2.5,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "I team ideano e realizzano scherzi divertenti ai passanti filmandoli di nascosto.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/candid-camera/"
    },
    {
        "nome": "Cardboard World",
        "format": "Costruzione / Creativo",
        "logistica": "Indoor",
        "target": "Ingegneri, Grandi Gruppi",
        "vibe": "Creatività, Visione, Costruzione",
        "hook": "Date forma alle vostre idee: costruiamo un mondo intero usando solo cartone e ingegno.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": 1000,
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione di strutture, mobili o scenari utilizzando solo cartone e creatività.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/cardboard-world/"
    },
    {
        "nome": "Carton Boat",
        "format": "Costruzione / Sport",
        "logistica": "Outdoor (Acqua)",
        "target": "Giovani, Sportivi, Summer Party",
        "vibe": "Risate, Sfida, Ingegno",
        "hook": "La sfida navale definitiva: galleggerà o affonderà? L'ingegno al potere.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione di barche di cartone che devono realmente galleggiare e gareggiare in acqua.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/carton-boat/"
    },
    {
        "nome": "Cartoon Car Race",
        "format": "Costruzione / Gara",
        "logistica": "Indoor / Outdoor",
        "target": "Tutti i reparti, Creativi",
        "vibe": "Risate, Competizione, Colore",
        "hook": "Tornare bambini per correre veloci: costruisci il tuo bolide e vinci la gara più pazza.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione e gara di auto a spinta realizzate in cartone e legno in stile cartoon.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/cartoon-car-race/"
    },
    {
        "nome": "Casinò",
        "format": "Intrattenimento",
        "logistica": "Indoor / Cena",
        "target": "Cene di Gala, Clienti VIP",
        "vibe": "Lusso, Gioco, Eleganza",
        "hook": "L'eleganza di Montecarlo al vostro evento: fate il vostro gioco, rien ne va plus!",
        "social_activity": True,
        "novita": False,
        "ranking": 2,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 3.0,
        "durata_ideale": 2.0,
        "descrizione": "Simulazione di una sala da gioco con tavoli reali (roulette, black jack) e croupier.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/casino/"
    },
    {
        "nome": "Caterpillar",
        "format": "Guida / Heavy",
        "logistica": "Outdoor",
        "target": "Uomini, Settore Edilizio/Tech",
        "vibe": "Potenza, Precisione, Wow Factor",
        "hook": "Mettetevi alla guida di veri giganti d'acciaio: potenza grezza sotto il vostro controllo.",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": 50,
        "durata_min": 3.0,
        "durata_max": 4.0,
        "durata_ideale": 3.5,
        "descrizione": "Prova di abilità e guida utilizzando veri mezzi pesanti da cantiere (escavatori).",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/caterpillar-day/"
    },
    {
        "nome": "Cena con Delitto",
        "format": "Investigativo / Cena",
        "logistica": "Durante i pasti",
        "target": "Cene Aziendali, Gruppi Analitici",
        "vibe": "Mistero, Intrigo, Coinvolgimento",
        "hook": "Il crimine è servito: tra una portata e l'altra, scoprite l'assassino seduto accanto a voi.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Spettacolo teatrale interattivo dove i commensali devono scoprire il colpevole di un crimine.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/cena-con-delitto/"
    },
    {
        "nome": "Chain Reaction",
        "format": "Costruzione / Logica",
        "logistica": "Indoor",
        "target": "Ingegneri, Project Manager",
        "vibe": "Logica, Pazienza, Wow Effect",
        "hook": "Ogni piccola azione conta: create la reazione a catena perfetta per unire i reparti.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione di un complesso meccanismo a catena dove ogni pezzo innesca il successivo.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/chain-reaction/"
    },
    {
        "nome": "Christmas Escape",
        "format": "Enigmi / Cena",
        "logistica": "Durante i pasti",
        "target": "Cene di Natale",
        "vibe": "Logica, Festa, Mistero",
        "hook": "Salvate il Natale risolvendo gli enigmi prima che arrivi il dolce!",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Escape room a tema natalizio con enigmi da risolvere al tavolo per aprire un lucchetto.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/christmas-escape/"
    },
    {
        "nome": "Cinema",
        "format": "Creativo / Video",
        "logistica": "Indoor / Outdoor",
        "target": "Marketing, HR, Creativi",
        "vibe": "Cinema, Recitazione, Teamwork",
        "hook": "Ciak, si gira! Trasformate i valori aziendali in un cortometraggio da Oscar.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 2.5,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Realizzazione di un cortometraggio: sceneggiatura, riprese, recitazione e montaggio.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/cinema/"
    },
    {
        "nome": "Cocktail Building",
        "format": "Culinario / Aperitivo",
        "logistica": "Indoor / Outdoor",
        "target": "Giovani, Aperitivi",
        "vibe": "Cool, Gusto, Relax",
        "hook": "Shakerate lo stress e create il mix perfetto per brindare al team.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Gara a squadre per creare il cocktail perfetto sotto la guida di barman professionisti.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/cocktail-building/"
    },
    {
        "nome": "Cooking",
        "format": "Culinario",
        "logistica": "Indoor",
        "target": "Tutti (eccetto intolleranze gravi)",
        "vibe": "Gusto, Collaborazione, Calore",
        "hook": "Dalla competizione ai fornelli alla condivisione a tavola: la ricetta segreta del team.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": 100,
        "durata_min": 1.0,
        "durata_max": 4.0,
        "durata_ideale": 2.0,
        "descrizione": "Gara di cucina completa (dalla spesa alla realizzazione del piatto) con chef professionisti.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/cooking/"
    },
    {
        "nome": "Cooking Mystery Box",
        "format": "Culinario",
        "logistica": "Indoor",
        "target": "Appassionati Masterchef",
        "vibe": "Adrenalina, Creatività, Gusto",
        "hook": "Ingredienti segreti, tempo limitato: scatenate la creatività culinaria!",
        "social_activity": False,
        "novita": True,
        "ranking": 5,
        "max_pax": 100,
        "durata_min": 2.5,
        "durata_max": 4.0,
        "durata_ideale": 3.5,
        "descrizione": "Sfida culinaria dove i team devono cucinare usando ingredienti segreti svelati all'ultimo.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/cooking-mystery-box/"
    },
    {
        "nome": "CSI Project",
        "format": "Investigativo",
        "logistica": "Indoor / Outdoor",
        "target": "Analitici, Problem Solvers",
        "vibe": "Mistero, Logica, Investigazione",
        "hook": "Sulla scena del crimine: usate la scienza forense per svelare la verità nascosta.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Indagine scientifica con rilevamento impronte, analisi prove e interrogatori.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/csi-project/"
    },
    {
        "nome": "Darkness Experience",
        "format": "Sensoriale",
        "logistica": "Indoor",
        "target": "Team che necessitano fiducia",
        "vibe": "Fiducia, Ascolto, Emozione profonda",
        "hook": "Spegnete la luce per accendere la fiducia: un'esperienza sensoriale profonda.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": 50,
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Attività sensoriali e di fiducia svolte nel buio totale per stimolare gli altri sensi.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/darkness-experience/"
    },
    {
        "nome": "Decode Fake News",
        "format": "Investigativo / Attualità",
        "logistica": "Indoor",
        "target": "Giornalisti, Comunicazione",
        "vibe": "Attualità, Critica, Dibattito",
        "hook": "Vero o falso? Allenate il pensiero critico nel labirinto dell'informazione.",
        "social_activity": False,
        "novita": True,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 2.0,
        "durata_ideale": 1.5,
        "descrizione": "Gioco di indagine per imparare a distinguere notizie vere da fake news (anche generate da AI).",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/decode-fake-news/"
    },
    {
        "nome": "Domino Rally",
        "format": "Costruzione / Pazienza",
        "logistica": "Indoor",
        "target": "Team pazienti, Precisione",
        "vibe": "Pazienza, Attenzione, Spettacolo",
        "hook": "Un lavoro di precisione millimetrica per un finale spettacolare e travolgente.",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Posizionamento di migliaia di tessere per creare un percorso a effetto domino.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/domino-rally/"
    },
    {
        "nome": "DragonBoat",
        "format": "Sport / Acqua",
        "logistica": "Outdoor (Lago)",
        "target": "Sportivi, Team numerosi",
        "vibe": "Sincronia, Forza, Natura",
        "hook": "Tutti allo stesso ritmo: la massima espressione della sincronia di squadra sull'acqua.",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Gara di velocità e sincronia su lunghe canoe a 10-20 posti a ritmo di tamburo.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/dragon-boat/"
    },
    {
        "nome": "Energy For Africa",
        "format": "Sociale / Tech",
        "logistica": "Indoor",
        "target": "CSR, Ingegneri",
        "vibe": "Tecnologia, Cuore, Impatto Sociale",
        "hook": "Accendiamo la luce dove serve: tecnologia e solidarietà si uniscono per cambiare vite.",
        "social_activity": True,
        "novita": True,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Assemblaggio di kit per l'energia solare che verranno donati a villaggi africani.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/energy-for-africa/"
    },
    {
        "nome": "Enigma",
        "format": "Avventura / Tech",
        "logistica": "Outdoor",
        "target": "Gruppi curiosi, Discovery",
        "vibe": "Dinamicità, Tecnologia, Sfida",
        "hook": "Un sapiente mix di attività per coinvolgere tutti, qualche prova più atletica e qualche prova mentale.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Attività outdoor/indoor per tutti i gusti, ottima per gruppi eterogenei non troppo sportivi.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/enigma/"
    },
    {
        "nome": "Escape Box",
        "format": "Logica / Enigmi",
        "logistica": "Indoor",
        "target": "Problem Solvers, Meeting",
        "vibe": "Tensione, Logica, Collaborazione",
        "hook": "La bomba sta ticchettando: avete il sangue freddo per disinnescarla in tempo?",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 1.5,
        "durata_ideale": 1.5,
        "descrizione": "Risoluzione di enigmi logici per aprire una valigetta o disinnescare una 'bomba'.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/escape-box/"
    },
    {
        "nome": "Family Day",
        "format": "Evento / Giochi",
        "logistica": "Indoor / Outdoor",
        "target": "Famiglie, Aziende inclusive",
        "vibe": "Gioia, Festa, Inclusione",
        "hook": "Aprite le porte alle famiglie: una giornata di festa dove lavoro e vita si incontrano.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 4.0,
        "durata_max": 8.0,
        "durata_ideale": 5.0,
        "descrizione": "Giornata di giochi, gonfiabili e attività aperta ai dipendenti e alle loro famiglie.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/family-day/"
    },
    {
        "nome": "Ferrari Challenge",
        "format": "Guida / Lusso",
        "logistica": "Outdoor (Pista)",
        "target": "Top Management, Clienti VIP",
        "vibe": "Lusso, Velocità, Esclusività",
        "hook": "Il sogno italiano in pista: domate i cavalli rampanti in un circuito esclusivo.",
        "social_activity": False,
        "novita": False,
        "ranking": 2,
        "max_pax": 60,
        "durata_min": 3.0,
        "durata_max": 6.0,
        "durata_ideale": 4.5,
        "descrizione": "Esperienza di guida in pista su vere auto da corsa Ferrari Challenge.",
        "formazione_level": "Low",
        "note": "Preventivo assolutamente indicativo, è per avere una idea del costo.",
        "url": "https://www.teambuilding.it/project/ferrari-challenge/"
    },
    {
        "nome": "Green Energy",
        "format": "Costruzione / Green",
        "logistica": "Indoor",
        "target": "Sostenibilità, Tech",
        "vibe": "Energia, Invenzione, Futuro",
        "hook": "Generare energia pulita con l'ingegno: la sfida energetica del futuro è nelle vostre mani.",
        "social_activity": True,
        "novita": True,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione di macchine capaci di generare energia pulita in modo creativo.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/green-energy/"
    },
    {
        "nome": "Green Grand Prix",
        "format": "RC Cars / Green",
        "logistica": "Indoor / Outdoor",
        "target": "Appassionati motori, Green",
        "vibe": "Velocità, Green, Competizione",
        "hook": "Gran Premio a impatto zero: velocità e divertimento con auto elettriche RC.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 3.0,
        "durata_ideale": 2.0,
        "descrizione": "Gara di velocità con auto radiocomandate elettriche su pista allestita.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/green-gran-prix/"
    },
    {
        "nome": "Guerrilla Gardening",
        "format": "Green / Sociale",
        "logistica": "Outdoor",
        "target": "CSR, Urban",
        "vibe": "Verde, Riqualificazione, Cura",
        "hook": "Un blitz verde per colorare la città e lasciare un segno positivo e duraturo.",
        "social_activity": True,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 5.0,
        "durata_ideale": 3.0,
        "descrizione": "Blitz verde urbano per piantare fiori e riqualificare aiuole abbandonate.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/guerrilla-gardening/"
    },
    {
        "nome": "Guida Neve/Ghiaccio",
        "format": "Guida",
        "logistica": "Outdoor (Neve)",
        "target": "Amanti guida, Inverno",
        "vibe": "Ghiaccio, Controllo, Drift",
        "hook": "Sfida il ghiaccio: impara a dominare l'auto nelle condizioni più estreme e scivolose.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": 60,
        "durata_min": 4.0,
        "durata_max": 8.0,
        "durata_ideale": 6.0,
        "descrizione": "Corso di guida sicura per imparare a gestire l'auto su neve e ghiaccio.",
        "formazione_level": "Low",
        "note": "Preventivo assolutamente indicativo.",
        "url": "https://www.teambuilding.it/project/guida-su-neve-e-ghiaccio/"
    },
    {
        "nome": "Hybrid Treasure Hunt",
        "format": "Tech / Discovery",
        "logistica": "Outdoor / Remoto",
        "target": "Team ibridi/remoti",
        "vibe": "Connessione, Scoperta, Tecnologia",
        "hook": "La caccia al tesoro 2.0: connettete chi è in ufficio con chi è in strada in tempo reale.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 3.0,
        "durata_ideale": 2.0,
        "descrizione": "Caccia al tesoro mista: una parte del team è in strada, l'altra guida da remoto.",
        "formazione_level": "Low",
        "note": "Preventivo assolutamente indicativo.",
        "url": "https://www.teambuilding.it/project/hybrid-treasure-hunt/"
    },
    {
        "nome": "Intelligenza Artificiale",
        "format": "Tech / AI",
        "logistica": "Indoor",
        "target": "Innovatori, Visionari",
        "vibe": "Tech, Futuro, Digital",
        "hook": "Umano + AI: la collaborazione definitiva per creare contenuti incredibili in pochi minuti.",
        "social_activity": False,
        "novita": True,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 1.0,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Utilizzo di strumenti AI per creare prodotti, immagini e campagne marketing.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/intelligenza-artificiale/"
    },
    {
        "nome": "Lego Building",
        "format": "Costruzione",
        "logistica": "Indoor",
        "target": "Ingegneri, Creativi, Tutti",
        "vibe": "Mattoncini, Nostalgia, Progettazione",
        "hook": "Tornare bambini per costruire il futuro dell'azienda, mattoncino su mattoncino.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Costruzione di sculture, loghi o progetti complessi con migliaia di mattoncini Lego.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/lego-building/"
    },
    {
        "nome": "Leonardo da Vinci",
        "format": "Costruzione",
        "logistica": "Indoor",
        "target": "Ingegneri, Storici",
        "vibe": "Genio, Storia, Meccanica",
        "hook": "Mettetevi alla prova con le invenzioni del più grande genio della storia.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Costruzione di macchine basate sui progetti di Leonardo (es. ponti, catapulte).",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/leonardo-da-vinci/"
    },
    {
        "nome": "Mission Impossible",
        "format": "Urban Game / Video",
        "logistica": "Outdoor",
        "target": "Giovani, Dinamici",
        "vibe": "Azione, Spionaggio, Città",
        "hook": "La vostra missione, se deciderete di accettarla: una caccia urbana ad alta tensione.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.5,
        "durata_ideale": 2.5,
        "descrizione": "Caccia al tesoro urbana con prove video creative da agenti segreti.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/mission-impossible/"
    },
    {
        "nome": "Movie Game",
        "format": "Quiz / Cinema",
        "logistica": "Durante i pasti",
        "target": "Cene Aziendali, Cinefili",
        "vibe": "Cinema, Quiz, Divertimento",
        "hook": "Vi sentite esperti di cinema? Mettetevi alla prova tra citazioni e colonne sonore!",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Quiz a squadre interattivo sul mondo del cinema con pulsantiere o app.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/movie-game/"
    },
    {
        "nome": "Mystery Box",
        "format": "Culinario",
        "logistica": "Indoor",
        "target": "Appassionati Masterchef",
        "vibe": "Adrenalina, Creatività, Gusto",
        "hook": "Una scatola misteriosa, ingredienti segreti e la sfida di creare un piatto da chef.",
        "social_activity": False,
        "novita": True,
        "ranking": 5,
        "max_pax": 100,
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Sfida di cucina in stile Masterchef con ingredienti a sorpresa.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/mystery-box/"
    },
    {
        "nome": "Olympic Games",
        "format": "Sportivo / Giochi",
        "logistica": "Outdoor",
        "target": "Sportivi, Grandi Gruppi",
        "vibe": "Competizione, Energia, Squadra",
        "hook": "Accendete la fiaccola: una serie di sfide olimpiche per celebrare lo spirito di squadra.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Olimpiadi aziendali con diverse discipline sportive e giochi di squadra.",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/olympic-games/"
    },
    {
        "nome": "Pasta Building",
        "format": "Culinario",
        "logistica": "Indoor",
        "target": "Gruppi Internazionali, Foodies",
        "vibe": "Tradizione, Manualità, Gusto",
        "hook": "Mani in pasta! Scoprite i segreti della tradizione italiana creando la pasta fresca.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": 100,
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Laboratorio pratico per imparare a fare la pasta fresca a mano (tagliatelle, ravioli).",
        "formazione_level": "Medium",
        "note": "",
        "url": "https://www.teambuilding.it/project/pasta-building/"
    },
    {
        "nome": "PiantiAmo",
        "format": "Green / Sociale",
        "logistica": "Outdoor",
        "target": "CSR, Green",
        "vibe": "Natura, Futuro, Radici",
        "hook": "Piantate oggi gli alberi che faranno respirare il domani.",
        "social_activity": True,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Attività di piantumazione di alberi in parchi o aree deforestate.",
        "formazione_level": "Medium",
        "note": "Prezzo indicativo, dipende dal tipo di piante.",
        "url": "https://www.teambuilding.it/project/guerrilla-gardening/"
    },
    {
        "nome": "Quizzone",
        "format": "Quiz / Cena",
        "logistica": "Durante i pasti",
        "target": "Cene Aziendali, Tutti",
        "vibe": "Cultura, Risate, Sfida",
        "hook": "Il classico dei classici: telecomandi alla mano, chi ne sa di più vince!",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 1.5,
        "durata_max": 2.5,
        "durata_ideale": 2.0,
        "descrizione": "Gioco a quiz multimediale con pulsantiere wireless al tavolo.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/quizzone/"
    },
    {
        "nome": "Sailing",
        "format": "Sport / Vela",
        "logistica": "Outdoor (Mare/Lago)",
        "target": "Board, Piccoli gruppi",
        "vibe": "Vento, Ruoli, Libertà",
        "hook": "Tutti sulla stessa barca: regolate le vele e tenete il timone verso l'obiettivo.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": 100,
        "durata_min": 3.0,
        "durata_max": 8.0,
        "durata_ideale": 4.0,
        "descrizione": "Regata velica o veleggiata con skipper professionisti su barche a vela.",
        "formazione_level": "Medium",
        "note": "Prezzo indicativo, dipende da diversi fattori quali la stagione e la località.",
        "url": "https://www.teambuilding.it/project/sailing/"
    },
    {
        "nome": "Shackleton",
        "format": "Formativo / Ghiaccio",
        "logistica": "Indoor",
        "target": "Manager, Team in crisi",
        "vibe": "Leadership, Crisi, Sopravvivenza",
        "hook": "Imparare a guidare nel ghiaccio: la lezione di leadership più estrema della storia.",
        "social_activity": False,
        "novita": False,
        "ranking": 5,
        "max_pax": 50,
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Team building formativo basato sulla storia della spedizione antartica di Shackleton.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/shackleton/"
    },
    {
        "nome": "Social Team Building",
        "format": "Sociale / CSR",
        "logistica": "Indoor / Outdoor",
        "target": "CSR, Aziende Etiche",
        "vibe": "Cuore, Utilità, Emozione",
        "hook": "Fate del bene, fatelo insieme. Un team building che lascia il segno nel cuore.",
        "social_activity": True,
        "novita": False,
        "ranking": 5,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 6.0,
        "durata_ideale": 4.0,
        "descrizione": "Attività generica di volontariato o supporto a onlus.",
        "formazione_level": "High",
        "note": "Prezzo indicativo, può variare in base al reale intervento.",
        "url": "https://www.teambuilding.it/project/social-team-building/"
    },
    {
        "nome": "Squid Game",
        "format": "Giochi / Serie TV",
        "logistica": "Indoor / Outdoor",
        "target": "Fan serie TV, Giovani",
        "vibe": "Tensione, Gioco, Trend",
        "hook": "Un, due, tre... Stella! Sopravvivete ai giochi dell'infanzia in versione corporate.",
        "social_activity": False,
        "novita": True,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 3.0,
        "durata_ideale": 2.5,
        "descrizione": "Serie di giochi a eliminazione ispirati alla famosa serie TV (senza violenza).",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/squid-game/"
    },
    {
        "nome": "Stuntman",
        "format": "Cinema / Azione",
        "logistica": "Outdoor",
        "target": "Audaci, Cinema",
        "vibe": "Azione, Cinema, Coraggio",
        "hook": "Luci, Motori, Azione! Diventate gli eroi di un film d'azione per un giorno.",
        "social_activity": False,
        "novita": False,
        "ranking": 3,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Laboratorio per imparare tecniche di stunt cinematografico (cadute, combattimenti finti).",
        "formazione_level": "Low",
        "note": "Prezzo indicativo, varia in base a diverse variabili.",
        "url": "https://www.teambuilding.it/project/stunt-man/"
    },
    {
        "nome": "Survival",
        "format": "Avventura / Natura",
        "logistica": "Outdoor",
        "target": "Avventurosi, Team Building puro",
        "vibe": "Natura, Fuoco, Sopravvivenza",
        "hook": "Dispersi nella natura: avete quello che serve per accendere il fuoco e sopravvivere?",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 3.0,
        "durata_max": 8.0,
        "durata_ideale": 4.0,
        "descrizione": "Corso di sopravvivenza: accensione fuoco, costruzione riparo, orientamento.",
        "formazione_level": "High",
        "note": "",
        "url": "https://www.teambuilding.it/project/survival/"
    },
    {
        "nome": "Treasure Hunt",
        "format": "Caccia al tesoro",
        "logistica": "Outdoor (Città)",
        "target": "Turisti, Gruppi Internazionali",
        "vibe": "Scoperta, Città, Gioco",
        "hook": "La città è il vostro tabellone di gioco: scopritene i tesori nascosti.",
        "social_activity": False,
        "novita": False,
        "ranking": 4,
        "max_pax": "Illimitato",
        "durata_min": 2.0,
        "durata_max": 4.0,
        "durata_ideale": 3.0,
        "descrizione": "Classica caccia al tesoro in città con mappa, indizi e tappe da raggiungere.",
        "formazione_level": "Low",
        "note": "",
        "url": "https://www.teambuilding.it/project/treasure-hunt/"
    },
    {
        "nome": "Yacht Day",
        "format": "Lusso / Mare",
        "logistica": "Outdoor",
        "target": "VIP, Top Management",
        "vibe": "Mare, Lusso, Sole",
        "hook": "Relax e lusso in mare aperto: un'esperienza esclusiva per chi punta all'eccellenza.",
        "social_activity": False,
        "novita": False,
        "ranking": 1,
        "max_pax": 10,
        "durata_min": 6.0,
        "durata_max": 8.0,
        "durata_ideale": 6.0,
        "descrizione": "Giornata in barca a motore di lusso con skipper e attività a bordo.",
        "formazione_level": "Medium",
        "note": "Prezzo indicativo, dipende molto dalla stagione.",
        "url": "https://www.teambuilding.it/project/yacht-day/"
    }
]
"""

# --- 4. AVVIO DELL'APP ---
genai.configure(api_key=api_key)

# SICUREZZA (Sblocco totale)
safety_settings = {
    HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
}

model = genai.GenerativeModel(
    model_name="gemini-1.5-flash",
    generation_config={"temperature": 0.0},
    # Qui uniamo le istruzioni e il database affinché l'AI veda tutto
    system_instruction=system_instruction + "\n" + database_attivita,
    safety_settings=safety_settings,
)

# INTERFACCIA
st.title("🏆 Timmy AI")
st.caption("Assistente Virtuale Senior - Uso Interno")

if "messages" not in st.session_state:
    st.session_state.messages = []
    welcome = "Ciao! Sono pronto. Dimmi numero pax, data e obiettivo."
    st.session_state.messages.append({"role": "model", "content": welcome})

# Mostra cronologia
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Input
if prompt := st.chat_input("Scrivi qui la richiesta..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Reset
    if prompt.lower().strip() in ["reset", "nuovo", "cancella", "stop"]:
        st.session_state.messages = []
        st.rerun()

    with st.chat_message("model"):
        with st.spinner("Elaborazione..."):
            try:
                history_gemini = []
                for m in st.session_state.messages:
                    if m["role"] != "model": 
                        history_gemini.append({"role": "user", "parts": [m["content"]]})
                    else:
                        history_gemini.append({"role": "model", "parts": [m["content"]]})
                
                chat = model.start_chat(history=history_gemini[:-1])
                response = chat.send_message(prompt)
                
                st.markdown(response.text)
                st.session_state.messages.append({"role": "model", "content": response.text})
                
            except Exception as e:
                st.error(f"Errore: {e}")


